# Generated by Django 5.2 on 2025-12-18 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the profile was created.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional information or bio of the user (optional).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                help_text="The user's first name.",
                max_length=50,
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Profile image of the user (optional).",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                help_text="The user's last name.",
                max_length=50,
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when the profile was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                help_text="The user associated with this profile.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the user was created.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can access the admin site.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the user's email address has been verified.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when the user was last updated.",
            ),
        ),
    ]
