# Generated by Django 5.2 on 2025-12-28 07:56

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Profile image of the user (optional).",
                null=True,
                upload_to=account.utils.profile_image_path,
            ),
        ),
    ]
